# Generated by Django 3.1.4 on 2020-12-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monkey',
            name='fleas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
